includes:
  - https://github.ibm.com/cloud-docs/cloud-infrastructure
  - https://github.ibm.com/cloud-docs/icons
translation:
  exclude:
    byFilePath:
      - file-dont-translate.md
      - folder-dont-translate/
